spring:
  application:
    name: spring-cloud-gateway-app

  cloud:
    gateway:
      routes:
#        - id: helloservice-route
#          uri: http://localhost:8071
#          predicates:
#            - Path=/rest/service/**
    
        - id: factorialservice-route
          uri: http://localhost:8073
          predicates:
            - Path=/factorial/service/**
        - id: productapi-client-route
          uri: http://localhost:8092
          predicates:
            - Path=/client/api1.0/**
            

server:
  port: 8072